
services:
  mongo:
    image: mongo:7.0
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    environment:
      MONGO_URI: ${MONGO_URI}
      NODE_ENV: ${NODE_ENV}
      PORT: ${PORT}
    ports:
      - "${PORT}:${PORT}"
    volumes:
       - ./api/.env:/usr/src/app/.env 
    depends_on:
      - mongo

volumes:
  mongo-data:
